{
  "abstract" : [
    {
      "text" : "AES encryption\/decryption methods.",
      "type" : "text"
    }
  ],
  "hierarchy" : {
    "paths" : [
      [
        "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore"
      ]
    ]
  },
  "identifier" : {
    "interfaceLanguage" : "swift",
    "url" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWAES"
  },
  "kind" : "symbol",
  "metadata" : {
    "externalID" : "c:@S@TWAES",
    "fragments" : [
      {
        "kind" : "keyword",
        "text" : "struct"
      },
      {
        "kind" : "text",
        "text" : " "
      },
      {
        "kind" : "identifier",
        "text" : "TWAES"
      }
    ],
    "modules" : [
      {
        "name" : "WalletCore"
      }
    ],
    "navigatorTitle" : [
      {
        "kind" : "identifier",
        "text" : "TWAES"
      }
    ],
    "role" : "symbol",
    "roleHeading" : "Structure",
    "symbolKind" : "struct",
    "title" : "TWAES"
  },
  "primaryContentSections" : [
    {
      "declarations" : [
        {
          "languages" : [
            "swift"
          ],
          "platforms" : [
            "iOS"
          ],
          "tokens" : [
            {
              "kind" : "keyword",
              "text" : "struct"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "identifier",
              "text" : "TWAES"
            }
          ]
        }
      ],
      "kind" : "declarations"
    }
  ],
  "relationshipsSections" : [
    {
      "identifiers" : [
        "doc:\/\/com.trustwallet.WalletCore\/s8SendableP"
      ],
      "kind" : "relationships",
      "title" : "Conforms To",
      "type" : "conformsTo"
    }
  ],
  "schemaVersion" : {
    "major" : 0,
    "minor" : 3,
    "patch" : 0
  },
  "sections" : [

  ],
  "topicSections" : [
    {
      "identifiers" : [
        "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWAES\/init()",
        "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWAES\/init(unused:)"
      ],
      "title" : "Initializers"
    },
    {
      "identifiers" : [
        "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWAES\/unused"
      ],
      "title" : "Instance Properties"
    }
  ],
  "variants" : [
    {
      "paths" : [
        "\/documentation\/walletcore\/twaes"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "swift"
        }
      ]
    },
    {
      "paths" : [
        "\/documentation\/walletcore\/twaes"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "occ"
        }
      ]
    }
  ]
, 
"references": {
"doc://com.trustwallet.WalletCore/documentation/WalletCore": {
  "abstract" : [

  ],
  "identifier" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "WalletCore",
  "type" : "topic",
  "url" : "\/documentation\/walletcore"
},
"doc://com.trustwallet.WalletCore/documentation/WalletCore/TWAES": {
  "abstract" : [
    {
      "text" : "AES encryption\/decryption methods.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "struct"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "TWAES"
    }
  ],
  "identifier" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWAES",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "TWAES"
    }
  ],
  "role" : "symbol",
  "title" : "TWAES",
  "type" : "topic",
  "url" : "\/documentation\/walletcore\/twaes"
},
"doc://com.trustwallet.WalletCore/documentation/WalletCore/TWAES/init()": {
  "abstract" : [

  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "init"
    },
    {
      "kind" : "text",
      "text" : "()"
    }
  ],
  "identifier" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWAES\/init()",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "init()",
  "type" : "topic",
  "url" : "\/documentation\/walletcore\/twaes\/init()"
},
"doc://com.trustwallet.WalletCore/documentation/WalletCore/TWAES/init(unused:)": {
  "abstract" : [

  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "init"
    },
    {
      "kind" : "text",
      "text" : "("
    },
    {
      "kind" : "externalParam",
      "text" : "unused"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:s5UInt8V",
      "text" : "UInt8"
    },
    {
      "kind" : "text",
      "text" : ")"
    }
  ],
  "identifier" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWAES\/init(unused:)",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "init(unused:)",
  "type" : "topic",
  "url" : "\/documentation\/walletcore\/twaes\/init(unused:)"
},
"doc://com.trustwallet.WalletCore/documentation/WalletCore/TWAES/unused": {
  "abstract" : [

  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "var"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "unused"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:s5UInt8V",
      "text" : "UInt8"
    }
  ],
  "identifier" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWAES\/unused",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "unused"
    }
  ],
  "role" : "symbol",
  "title" : "unused",
  "type" : "topic",
  "url" : "\/documentation\/walletcore\/twaes\/unused"
},
"doc://com.trustwallet.WalletCore/s8SendableP": {
  "identifier" : "doc:\/\/com.trustwallet.WalletCore\/s8SendableP",
  "title" : "Swift.Sendable",
  "type" : "unresolvable"
}
}, 
"variantOverrides":[
  {
    "patch" : [
      {
        "op" : "replace",
        "path" : "\/identifier\/interfaceLanguage",
        "value" : "occ"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/roleHeading",
        "value" : "Structure"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/title",
        "value" : "TWAES"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/symbolKind",
        "value" : "struct"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "TWAES"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "TWAES"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/topicSections",
        "value" : [
          {
            "identifiers" : [
              "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWAES\/unused"
            ],
            "title" : "Instance Properties"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/relationshipsSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/seeAlsoSections",
        "value" : null
      },
      {
        "op" : "replace",
        "path" : "\/primaryContentSections\/0",
        "value" : {
          "declarations" : [
            {
              "languages" : [
                "occ"
              ],
              "platforms" : [
                "iOS"
              ],
              "tokens" : [
                {
                  "kind" : "keyword",
                  "text" : "struct"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "kind" : "identifier",
                  "text" : "TWAES"
                }
              ]
            }
          ],
          "kind" : "declarations"
        }
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.trustwallet.WalletCore~1documentation~1WalletCore~1TWAES\/title",
        "value" : "TWAES"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.trustwallet.WalletCore~1documentation~1WalletCore~1TWAES\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "TWAES"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.trustwallet.WalletCore~1documentation~1WalletCore~1TWAES~1unused\/title",
        "value" : "unused"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.trustwallet.WalletCore~1documentation~1WalletCore~1TWAES~1unused\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "unused"
          }
        ]
      }
    ],
    "traits" : [
      {
        "interfaceLanguage" : "occ"
      }
    ]
  }
]
}