{
  "abstract" : [
    {
      "text" : "Creates an address from a public key and derivation option.",
      "type" : "text"
    }
  ],
  "hierarchy" : {
    "paths" : [
      [
        "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore"
      ]
    ]
  },
  "identifier" : {
    "interfaceLanguage" : "swift",
    "url" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWAnyAddressCreateWithPublicKeyDerivation(_:_:_:)"
  },
  "kind" : "symbol",
  "metadata" : {
    "externalID" : "c:@F@TWAnyAddressCreateWithPublicKeyDerivation",
    "fragments" : [
      {
        "kind" : "keyword",
        "text" : "func"
      },
      {
        "kind" : "text",
        "text" : " "
      },
      {
        "kind" : "identifier",
        "text" : "TWAnyAddressCreateWithPublicKeyDerivation"
      },
      {
        "kind" : "text",
        "text" : "("
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "s:s13OpaquePointerV",
        "text" : "OpaquePointer"
      },
      {
        "kind" : "text",
        "text" : ", "
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "c:@E@TWCoinType",
        "text" : "TWCoinType"
      },
      {
        "kind" : "text",
        "text" : ", "
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "c:@E@TWDerivation",
        "text" : "TWDerivation"
      },
      {
        "kind" : "text",
        "text" : ") -> "
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "s:s13OpaquePointerV",
        "text" : "OpaquePointer"
      }
    ],
    "modules" : [
      {
        "name" : "WalletCore"
      }
    ],
    "navigatorTitle" : [
      {
        "kind" : "identifier",
        "text" : "TWAnyAddressCreateWithPublicKeyDerivation"
      }
    ],
    "role" : "symbol",
    "roleHeading" : "Function",
    "symbolKind" : "func",
    "title" : "TWAnyAddressCreateWithPublicKeyDerivation(_:_:_:)"
  },
  "primaryContentSections" : [
    {
      "declarations" : [
        {
          "languages" : [
            "swift"
          ],
          "platforms" : [
            "iOS"
          ],
          "tokens" : [
            {
              "kind" : "keyword",
              "text" : "func"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "identifier",
              "text" : "TWAnyAddressCreateWithPublicKeyDerivation"
            },
            {
              "kind" : "text",
              "text" : "("
            },
            {
              "kind" : "externalParam",
              "text" : "_"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "internalParam",
              "text" : "publicKey"
            },
            {
              "kind" : "text",
              "text" : ": "
            },
            {
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "s:s13OpaquePointerV",
              "text" : "OpaquePointer"
            },
            {
              "kind" : "text",
              "text" : ", "
            },
            {
              "kind" : "externalParam",
              "text" : "_"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "internalParam",
              "text" : "coin"
            },
            {
              "kind" : "text",
              "text" : ": "
            },
            {
              "identifier" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWCoinType",
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "c:@E@TWCoinType",
              "text" : "TWCoinType"
            },
            {
              "kind" : "text",
              "text" : ", "
            },
            {
              "kind" : "externalParam",
              "text" : "_"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "internalParam",
              "text" : "derivation"
            },
            {
              "kind" : "text",
              "text" : ": "
            },
            {
              "identifier" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWDerivation",
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "c:@E@TWDerivation",
              "text" : "TWDerivation"
            },
            {
              "kind" : "text",
              "text" : ") -> "
            },
            {
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "s:s13OpaquePointerV",
              "text" : "OpaquePointer"
            }
          ]
        }
      ],
      "kind" : "declarations"
    },
    {
      "content" : [
        {
          "anchor" : "discussion",
          "level" : 2,
          "text" : "Discussion",
          "type" : "heading"
        },
        {
          "inlineContent" : [
            {
              "text" : "\\param publicKey derivates the address from the public key.",
              "type" : "text"
            },
            {
              "text" : " ",
              "type" : "text"
            },
            {
              "text" : "\\param coin coin type of the address.",
              "type" : "text"
            },
            {
              "text" : " ",
              "type" : "text"
            },
            {
              "text" : "\\param derivation the custom derivation to use.",
              "type" : "text"
            },
            {
              "text" : " ",
              "type" : "text"
            },
            {
              "text" : "\\return TWAnyAddress pointer or nullptr if public key is invalid.",
              "type" : "text"
            }
          ],
          "type" : "paragraph"
        }
      ],
      "kind" : "content"
    }
  ],
  "schemaVersion" : {
    "major" : 0,
    "minor" : 3,
    "patch" : 0
  },
  "sections" : [

  ],
  "variants" : [
    {
      "paths" : [
        "\/documentation\/walletcore\/twanyaddresscreatewithpublickeyderivation(_:_:_:)"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "swift"
        }
      ]
    },
    {
      "paths" : [
        "\/documentation\/walletcore\/twanyaddresscreatewithpublickeyderivation(_:_:_:)"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "occ"
        }
      ]
    }
  ]
, 
"references": {
"doc://com.trustwallet.WalletCore/documentation/WalletCore": {
  "abstract" : [

  ],
  "identifier" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "WalletCore",
  "type" : "topic",
  "url" : "\/documentation\/walletcore"
},
"doc://com.trustwallet.WalletCore/documentation/WalletCore/TWAnyAddressCreateWithPublicKeyDerivation(_:_:_:)": {
  "abstract" : [
    {
      "text" : "Creates an address from a public key and derivation option.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "func"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "TWAnyAddressCreateWithPublicKeyDerivation"
    },
    {
      "kind" : "text",
      "text" : "("
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:s13OpaquePointerV",
      "text" : "OpaquePointer"
    },
    {
      "kind" : "text",
      "text" : ", "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "c:@E@TWCoinType",
      "text" : "TWCoinType"
    },
    {
      "kind" : "text",
      "text" : ", "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "c:@E@TWDerivation",
      "text" : "TWDerivation"
    },
    {
      "kind" : "text",
      "text" : ") -> "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:s13OpaquePointerV",
      "text" : "OpaquePointer"
    }
  ],
  "identifier" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWAnyAddressCreateWithPublicKeyDerivation(_:_:_:)",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "TWAnyAddressCreateWithPublicKeyDerivation"
    }
  ],
  "role" : "symbol",
  "title" : "TWAnyAddressCreateWithPublicKeyDerivation(_:_:_:)",
  "type" : "topic",
  "url" : "\/documentation\/walletcore\/twanyaddresscreatewithpublickeyderivation(_:_:_:)"
},
"doc://com.trustwallet.WalletCore/documentation/WalletCore/TWCoinType": {
  "abstract" : [
    {
      "text" : "Coin type for Level 2 of BIP44.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "struct"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "TWCoinType"
    }
  ],
  "identifier" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWCoinType",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "TWCoinType"
    }
  ],
  "role" : "symbol",
  "title" : "TWCoinType",
  "type" : "topic",
  "url" : "\/documentation\/walletcore\/twcointype"
},
"doc://com.trustwallet.WalletCore/documentation/WalletCore/TWDerivation": {
  "abstract" : [
    {
      "text" : "Non-default coin address derivation names (default, unnamed derivations are not included).",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "struct"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "TWDerivation"
    }
  ],
  "identifier" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWDerivation",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "TWDerivation"
    }
  ],
  "role" : "symbol",
  "title" : "TWDerivation",
  "type" : "topic",
  "url" : "\/documentation\/walletcore\/twderivation"
}
}, 
"variantOverrides":[
  {
    "patch" : [
      {
        "op" : "replace",
        "path" : "\/identifier\/interfaceLanguage",
        "value" : "occ"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/roleHeading",
        "value" : "Function"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/title",
        "value" : "TWAnyAddressCreateWithPublicKeyDerivation"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/symbolKind",
        "value" : "func"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "TWAnyAddressCreateWithPublicKeyDerivation"
          }
        ]
      },
      {
        "op" : "add",
        "path" : "\/topicSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/relationshipsSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/seeAlsoSections",
        "value" : null
      },
      {
        "op" : "replace",
        "path" : "\/primaryContentSections\/0",
        "value" : {
          "declarations" : [
            {
              "languages" : [
                "occ"
              ],
              "platforms" : [
                "iOS"
              ],
              "tokens" : [
                {
                  "kind" : "keyword",
                  "text" : "extern"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "kind" : "keyword",
                  "text" : "struct"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:@S@TWAnyAddress",
                  "text" : "TWAnyAddress"
                },
                {
                  "kind" : "text",
                  "text" : " * "
                },
                {
                  "kind" : "identifier",
                  "text" : "TWAnyAddressCreateWithPublicKeyDerivation"
                },
                {
                  "kind" : "text",
                  "text" : "("
                },
                {
                  "kind" : "keyword",
                  "text" : "struct"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:@S@TWPublicKey",
                  "text" : "TWPublicKey"
                },
                {
                  "kind" : "text",
                  "text" : " * "
                },
                {
                  "kind" : "internalParam",
                  "text" : "publicKey"
                },
                {
                  "kind" : "text",
                  "text" : ", "
                },
                {
                  "kind" : "keyword",
                  "text" : "enum"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "identifier" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWCoinType",
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:@E@TWCoinType",
                  "text" : "TWCoinType"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "kind" : "internalParam",
                  "text" : "coin"
                },
                {
                  "kind" : "text",
                  "text" : ", "
                },
                {
                  "kind" : "keyword",
                  "text" : "enum"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "identifier" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWDerivation",
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:@E@TWDerivation",
                  "text" : "TWDerivation"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "kind" : "internalParam",
                  "text" : "derivation"
                },
                {
                  "kind" : "text",
                  "text" : ")"
                }
              ]
            }
          ],
          "kind" : "declarations"
        }
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.trustwallet.WalletCore~1documentation~1WalletCore~1TWAnyAddressCreateWithPublicKeyDerivation(_:_:_:)\/title",
        "value" : "TWAnyAddressCreateWithPublicKeyDerivation"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.trustwallet.WalletCore~1documentation~1WalletCore~1TWAnyAddressCreateWithPublicKeyDerivation(_:_:_:)\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "TWAnyAddressCreateWithPublicKeyDerivation"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.trustwallet.WalletCore~1documentation~1WalletCore~1TWCoinType\/title",
        "value" : "TWCoinType"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.trustwallet.WalletCore~1documentation~1WalletCore~1TWCoinType\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "TWCoinType"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.trustwallet.WalletCore~1documentation~1WalletCore~1TWDerivation\/title",
        "value" : "TWDerivation"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.trustwallet.WalletCore~1documentation~1WalletCore~1TWDerivation\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "TWDerivation"
          }
        ]
      }
    ],
    "traits" : [
      {
        "interfaceLanguage" : "occ"
      }
    ]
  }
]
}