{
  "abstract" : [
    {
      "text" : "Adding a uint8 type parameter of to the top-level input parameter array",
      "type" : "text"
    }
  ],
  "hierarchy" : {
    "paths" : [
      [
        "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore"
      ]
    ]
  },
  "identifier" : {
    "interfaceLanguage" : "swift",
    "url" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWEthereumAbiFunctionAddInArrayParamUInt8(_:_:_:)"
  },
  "kind" : "symbol",
  "metadata" : {
    "externalID" : "c:@F@TWEthereumAbiFunctionAddInArrayParamUInt8",
    "fragments" : [
      {
        "kind" : "keyword",
        "text" : "func"
      },
      {
        "kind" : "text",
        "text" : " "
      },
      {
        "kind" : "identifier",
        "text" : "TWEthereumAbiFunctionAddInArrayParamUInt8"
      },
      {
        "kind" : "text",
        "text" : "("
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "s:s13OpaquePointerV",
        "text" : "OpaquePointer"
      },
      {
        "kind" : "text",
        "text" : ", "
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "s:s5Int32V",
        "text" : "Int32"
      },
      {
        "kind" : "text",
        "text" : ", "
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "s:s5UInt8V",
        "text" : "UInt8"
      },
      {
        "kind" : "text",
        "text" : ") -> "
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "s:s5Int32V",
        "text" : "Int32"
      }
    ],
    "modules" : [
      {
        "name" : "WalletCore"
      }
    ],
    "navigatorTitle" : [
      {
        "kind" : "identifier",
        "text" : "TWEthereumAbiFunctionAddInArrayParamUInt8"
      }
    ],
    "role" : "symbol",
    "roleHeading" : "Function",
    "symbolKind" : "func",
    "title" : "TWEthereumAbiFunctionAddInArrayParamUInt8(_:_:_:)"
  },
  "primaryContentSections" : [
    {
      "declarations" : [
        {
          "languages" : [
            "swift"
          ],
          "platforms" : [
            "iOS"
          ],
          "tokens" : [
            {
              "kind" : "keyword",
              "text" : "func"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "identifier",
              "text" : "TWEthereumAbiFunctionAddInArrayParamUInt8"
            },
            {
              "kind" : "text",
              "text" : "("
            },
            {
              "kind" : "externalParam",
              "text" : "_"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "internalParam",
              "text" : "fn"
            },
            {
              "kind" : "text",
              "text" : ": "
            },
            {
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "s:s13OpaquePointerV",
              "text" : "OpaquePointer"
            },
            {
              "kind" : "text",
              "text" : ", "
            },
            {
              "kind" : "externalParam",
              "text" : "_"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "internalParam",
              "text" : "arrayIdx"
            },
            {
              "kind" : "text",
              "text" : ": "
            },
            {
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "s:s5Int32V",
              "text" : "Int32"
            },
            {
              "kind" : "text",
              "text" : ", "
            },
            {
              "kind" : "externalParam",
              "text" : "_"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "internalParam",
              "text" : "val"
            },
            {
              "kind" : "text",
              "text" : ": "
            },
            {
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "s:s5UInt8V",
              "text" : "UInt8"
            },
            {
              "kind" : "text",
              "text" : ") -> "
            },
            {
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "s:s5Int32V",
              "text" : "Int32"
            }
          ]
        }
      ],
      "kind" : "declarations"
    },
    {
      "content" : [
        {
          "anchor" : "discussion",
          "level" : 2,
          "text" : "Discussion",
          "type" : "heading"
        },
        {
          "inlineContent" : [
            {
              "text" : "\\param fn A Non-null eth abi function",
              "type" : "text"
            },
            {
              "text" : " ",
              "type" : "text"
            },
            {
              "text" : "\\param arrayIdx array index for the abi function (0-based).",
              "type" : "text"
            },
            {
              "text" : " ",
              "type" : "text"
            },
            {
              "text" : "\\param val the value of the parameter",
              "type" : "text"
            },
            {
              "text" : " ",
              "type" : "text"
            },
            {
              "text" : "\\return the index of the added parameter (0-based).",
              "type" : "text"
            }
          ],
          "type" : "paragraph"
        }
      ],
      "kind" : "content"
    }
  ],
  "schemaVersion" : {
    "major" : 0,
    "minor" : 3,
    "patch" : 0
  },
  "sections" : [

  ],
  "variants" : [
    {
      "paths" : [
        "\/documentation\/walletcore\/twethereumabifunctionaddinarrayparamuint8(_:_:_:)"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "swift"
        }
      ]
    },
    {
      "paths" : [
        "\/documentation\/walletcore\/twethereumabifunctionaddinarrayparamuint8(_:_:_:)"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "occ"
        }
      ]
    }
  ]
, 
"references": {
"doc://com.trustwallet.WalletCore/documentation/WalletCore": {
  "abstract" : [

  ],
  "identifier" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "WalletCore",
  "type" : "topic",
  "url" : "\/documentation\/walletcore"
},
"doc://com.trustwallet.WalletCore/documentation/WalletCore/TWEthereumAbiFunctionAddInArrayParamUInt8(_:_:_:)": {
  "abstract" : [
    {
      "text" : "Adding a uint8 type parameter of to the top-level input parameter array",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "func"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "TWEthereumAbiFunctionAddInArrayParamUInt8"
    },
    {
      "kind" : "text",
      "text" : "("
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:s13OpaquePointerV",
      "text" : "OpaquePointer"
    },
    {
      "kind" : "text",
      "text" : ", "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:s5Int32V",
      "text" : "Int32"
    },
    {
      "kind" : "text",
      "text" : ", "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:s5UInt8V",
      "text" : "UInt8"
    },
    {
      "kind" : "text",
      "text" : ") -> "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:s5Int32V",
      "text" : "Int32"
    }
  ],
  "identifier" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWEthereumAbiFunctionAddInArrayParamUInt8(_:_:_:)",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "TWEthereumAbiFunctionAddInArrayParamUInt8"
    }
  ],
  "role" : "symbol",
  "title" : "TWEthereumAbiFunctionAddInArrayParamUInt8(_:_:_:)",
  "type" : "topic",
  "url" : "\/documentation\/walletcore\/twethereumabifunctionaddinarrayparamuint8(_:_:_:)"
}
}, 
"variantOverrides":[
  {
    "patch" : [
      {
        "op" : "replace",
        "path" : "\/identifier\/interfaceLanguage",
        "value" : "occ"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/roleHeading",
        "value" : "Function"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/title",
        "value" : "TWEthereumAbiFunctionAddInArrayParamUInt8"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/symbolKind",
        "value" : "func"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "TWEthereumAbiFunctionAddInArrayParamUInt8"
          }
        ]
      },
      {
        "op" : "add",
        "path" : "\/topicSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/relationshipsSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/seeAlsoSections",
        "value" : null
      },
      {
        "op" : "replace",
        "path" : "\/primaryContentSections\/0",
        "value" : {
          "declarations" : [
            {
              "languages" : [
                "occ"
              ],
              "platforms" : [
                "iOS"
              ],
              "tokens" : [
                {
                  "kind" : "keyword",
                  "text" : "extern"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:I",
                  "text" : "int"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "kind" : "identifier",
                  "text" : "TWEthereumAbiFunctionAddInArrayParamUInt8"
                },
                {
                  "kind" : "text",
                  "text" : "("
                },
                {
                  "kind" : "keyword",
                  "text" : "struct"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:@S@TWEthereumAbiFunction",
                  "text" : "TWEthereumAbiFunction"
                },
                {
                  "kind" : "text",
                  "text" : " * "
                },
                {
                  "kind" : "internalParam",
                  "text" : "fn"
                },
                {
                  "kind" : "text",
                  "text" : ", "
                },
                {
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:I",
                  "text" : "int"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "kind" : "internalParam",
                  "text" : "arrayIdx"
                },
                {
                  "kind" : "text",
                  "text" : ", "
                },
                {
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:@T@uint8_t",
                  "text" : "uint8_t"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "kind" : "internalParam",
                  "text" : "val"
                },
                {
                  "kind" : "text",
                  "text" : ")"
                }
              ]
            }
          ],
          "kind" : "declarations"
        }
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.trustwallet.WalletCore~1documentation~1WalletCore~1TWEthereumAbiFunctionAddInArrayParamUInt8(_:_:_:)\/title",
        "value" : "TWEthereumAbiFunctionAddInArrayParamUInt8"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.trustwallet.WalletCore~1documentation~1WalletCore~1TWEthereumAbiFunctionAddInArrayParamUInt8(_:_:_:)\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "TWEthereumAbiFunctionAddInArrayParamUInt8"
          }
        ]
      }
    ],
    "traits" : [
      {
        "interfaceLanguage" : "occ"
      }
    ]
  }
]
}