{
  "abstract" : [
    {
      "text" : "Add a uint32 type parameter",
      "type" : "text"
    }
  ],
  "hierarchy" : {
    "paths" : [
      [
        "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore"
      ]
    ]
  },
  "identifier" : {
    "interfaceLanguage" : "swift",
    "url" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWEthereumAbiFunctionAddParamUInt32(_:_:_:)"
  },
  "kind" : "symbol",
  "metadata" : {
    "externalID" : "c:@F@TWEthereumAbiFunctionAddParamUInt32",
    "fragments" : [
      {
        "kind" : "keyword",
        "text" : "func"
      },
      {
        "kind" : "text",
        "text" : " "
      },
      {
        "kind" : "identifier",
        "text" : "TWEthereumAbiFunctionAddParamUInt32"
      },
      {
        "kind" : "text",
        "text" : "("
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "s:s13OpaquePointerV",
        "text" : "OpaquePointer"
      },
      {
        "kind" : "text",
        "text" : ", "
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "s:s6UInt32V",
        "text" : "UInt32"
      },
      {
        "kind" : "text",
        "text" : ", "
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "s:Sb",
        "text" : "Bool"
      },
      {
        "kind" : "text",
        "text" : ") -> "
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "s:s5Int32V",
        "text" : "Int32"
      }
    ],
    "modules" : [
      {
        "name" : "WalletCore"
      }
    ],
    "navigatorTitle" : [
      {
        "kind" : "identifier",
        "text" : "TWEthereumAbiFunctionAddParamUInt32"
      }
    ],
    "role" : "symbol",
    "roleHeading" : "Function",
    "symbolKind" : "func",
    "title" : "TWEthereumAbiFunctionAddParamUInt32(_:_:_:)"
  },
  "primaryContentSections" : [
    {
      "declarations" : [
        {
          "languages" : [
            "swift"
          ],
          "platforms" : [
            "iOS"
          ],
          "tokens" : [
            {
              "kind" : "keyword",
              "text" : "func"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "identifier",
              "text" : "TWEthereumAbiFunctionAddParamUInt32"
            },
            {
              "kind" : "text",
              "text" : "("
            },
            {
              "kind" : "externalParam",
              "text" : "_"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "internalParam",
              "text" : "fn"
            },
            {
              "kind" : "text",
              "text" : ": "
            },
            {
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "s:s13OpaquePointerV",
              "text" : "OpaquePointer"
            },
            {
              "kind" : "text",
              "text" : ", "
            },
            {
              "kind" : "externalParam",
              "text" : "_"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "internalParam",
              "text" : "val"
            },
            {
              "kind" : "text",
              "text" : ": "
            },
            {
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "s:s6UInt32V",
              "text" : "UInt32"
            },
            {
              "kind" : "text",
              "text" : ", "
            },
            {
              "kind" : "externalParam",
              "text" : "_"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "internalParam",
              "text" : "isOutput"
            },
            {
              "kind" : "text",
              "text" : ": "
            },
            {
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "s:Sb",
              "text" : "Bool"
            },
            {
              "kind" : "text",
              "text" : ") -> "
            },
            {
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "s:s5Int32V",
              "text" : "Int32"
            }
          ]
        }
      ],
      "kind" : "declarations"
    },
    {
      "content" : [
        {
          "anchor" : "discussion",
          "level" : 2,
          "text" : "Discussion",
          "type" : "heading"
        },
        {
          "inlineContent" : [
            {
              "text" : "\\param fn A Non-null eth abi function",
              "type" : "text"
            },
            {
              "text" : " ",
              "type" : "text"
            },
            {
              "text" : "\\param val for output parameters, value has to be specified",
              "type" : "text"
            },
            {
              "text" : " ",
              "type" : "text"
            },
            {
              "text" : "\\param isOutput determines if the parameter is an input or output",
              "type" : "text"
            },
            {
              "text" : " ",
              "type" : "text"
            },
            {
              "text" : "\\return the index of the parameter (0-based).",
              "type" : "text"
            }
          ],
          "type" : "paragraph"
        }
      ],
      "kind" : "content"
    }
  ],
  "schemaVersion" : {
    "major" : 0,
    "minor" : 3,
    "patch" : 0
  },
  "sections" : [

  ],
  "variants" : [
    {
      "paths" : [
        "\/documentation\/walletcore\/twethereumabifunctionaddparamuint32(_:_:_:)"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "swift"
        }
      ]
    },
    {
      "paths" : [
        "\/documentation\/walletcore\/twethereumabifunctionaddparamuint32(_:_:_:)"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "occ"
        }
      ]
    }
  ]
, 
"references": {
"doc://com.trustwallet.WalletCore/documentation/WalletCore": {
  "abstract" : [

  ],
  "identifier" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "WalletCore",
  "type" : "topic",
  "url" : "\/documentation\/walletcore"
},
"doc://com.trustwallet.WalletCore/documentation/WalletCore/TWEthereumAbiFunctionAddParamUInt32(_:_:_:)": {
  "abstract" : [
    {
      "text" : "Add a uint32 type parameter",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "func"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "TWEthereumAbiFunctionAddParamUInt32"
    },
    {
      "kind" : "text",
      "text" : "("
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:s13OpaquePointerV",
      "text" : "OpaquePointer"
    },
    {
      "kind" : "text",
      "text" : ", "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:s6UInt32V",
      "text" : "UInt32"
    },
    {
      "kind" : "text",
      "text" : ", "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:Sb",
      "text" : "Bool"
    },
    {
      "kind" : "text",
      "text" : ") -> "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:s5Int32V",
      "text" : "Int32"
    }
  ],
  "identifier" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWEthereumAbiFunctionAddParamUInt32(_:_:_:)",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "TWEthereumAbiFunctionAddParamUInt32"
    }
  ],
  "role" : "symbol",
  "title" : "TWEthereumAbiFunctionAddParamUInt32(_:_:_:)",
  "type" : "topic",
  "url" : "\/documentation\/walletcore\/twethereumabifunctionaddparamuint32(_:_:_:)"
}
}, 
"variantOverrides":[
  {
    "patch" : [
      {
        "op" : "replace",
        "path" : "\/identifier\/interfaceLanguage",
        "value" : "occ"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/roleHeading",
        "value" : "Function"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/title",
        "value" : "TWEthereumAbiFunctionAddParamUInt32"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/symbolKind",
        "value" : "func"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "TWEthereumAbiFunctionAddParamUInt32"
          }
        ]
      },
      {
        "op" : "add",
        "path" : "\/topicSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/relationshipsSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/seeAlsoSections",
        "value" : null
      },
      {
        "op" : "replace",
        "path" : "\/primaryContentSections\/0",
        "value" : {
          "declarations" : [
            {
              "languages" : [
                "occ"
              ],
              "platforms" : [
                "iOS"
              ],
              "tokens" : [
                {
                  "kind" : "keyword",
                  "text" : "extern"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:I",
                  "text" : "int"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "kind" : "identifier",
                  "text" : "TWEthereumAbiFunctionAddParamUInt32"
                },
                {
                  "kind" : "text",
                  "text" : "("
                },
                {
                  "kind" : "keyword",
                  "text" : "struct"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:@S@TWEthereumAbiFunction",
                  "text" : "TWEthereumAbiFunction"
                },
                {
                  "kind" : "text",
                  "text" : " * "
                },
                {
                  "kind" : "internalParam",
                  "text" : "fn"
                },
                {
                  "kind" : "text",
                  "text" : ", "
                },
                {
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:@T@uint32_t",
                  "text" : "uint32_t"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "kind" : "internalParam",
                  "text" : "val"
                },
                {
                  "kind" : "text",
                  "text" : ", "
                },
                {
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:b",
                  "text" : "_Bool"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "kind" : "internalParam",
                  "text" : "isOutput"
                },
                {
                  "kind" : "text",
                  "text" : ")"
                }
              ]
            }
          ],
          "kind" : "declarations"
        }
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.trustwallet.WalletCore~1documentation~1WalletCore~1TWEthereumAbiFunctionAddParamUInt32(_:_:_:)\/title",
        "value" : "TWEthereumAbiFunctionAddParamUInt32"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.trustwallet.WalletCore~1documentation~1WalletCore~1TWEthereumAbiFunctionAddParamUInt32(_:_:_:)\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "TWEthereumAbiFunctionAddParamUInt32"
          }
        ]
      }
    ],
    "traits" : [
      {
        "interfaceLanguage" : "occ"
      }
    ]
  }
]
}