{
  "abstract" : [
    {
      "text" : "Creates a segwit-version-0 address from a public key and HRP prefix.",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "Taproot (v>=1) is not supported by this method.",
      "type" : "text"
    }
  ],
  "hierarchy" : {
    "paths" : [
      [
        "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore"
      ]
    ]
  },
  "identifier" : {
    "interfaceLanguage" : "swift",
    "url" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWSegwitAddressCreateWithPublicKey(_:_:)"
  },
  "kind" : "symbol",
  "metadata" : {
    "externalID" : "c:@F@TWSegwitAddressCreateWithPublicKey",
    "fragments" : [
      {
        "kind" : "keyword",
        "text" : "func"
      },
      {
        "kind" : "text",
        "text" : " "
      },
      {
        "kind" : "identifier",
        "text" : "TWSegwitAddressCreateWithPublicKey"
      },
      {
        "kind" : "text",
        "text" : "("
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "c:@E@TWHRP",
        "text" : "TWHRP"
      },
      {
        "kind" : "text",
        "text" : ", "
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "s:s13OpaquePointerV",
        "text" : "OpaquePointer"
      },
      {
        "kind" : "text",
        "text" : ") -> "
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "s:s13OpaquePointerV",
        "text" : "OpaquePointer"
      }
    ],
    "modules" : [
      {
        "name" : "WalletCore"
      }
    ],
    "navigatorTitle" : [
      {
        "kind" : "identifier",
        "text" : "TWSegwitAddressCreateWithPublicKey"
      }
    ],
    "role" : "symbol",
    "roleHeading" : "Function",
    "symbolKind" : "func",
    "title" : "TWSegwitAddressCreateWithPublicKey(_:_:)"
  },
  "primaryContentSections" : [
    {
      "declarations" : [
        {
          "languages" : [
            "swift"
          ],
          "platforms" : [
            "iOS"
          ],
          "tokens" : [
            {
              "kind" : "keyword",
              "text" : "func"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "identifier",
              "text" : "TWSegwitAddressCreateWithPublicKey"
            },
            {
              "kind" : "text",
              "text" : "("
            },
            {
              "kind" : "externalParam",
              "text" : "_"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "internalParam",
              "text" : "hrp"
            },
            {
              "kind" : "text",
              "text" : ": "
            },
            {
              "identifier" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWHRP",
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "c:@E@TWHRP",
              "text" : "TWHRP"
            },
            {
              "kind" : "text",
              "text" : ", "
            },
            {
              "kind" : "externalParam",
              "text" : "_"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "internalParam",
              "text" : "publicKey"
            },
            {
              "kind" : "text",
              "text" : ": "
            },
            {
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "s:s13OpaquePointerV",
              "text" : "OpaquePointer"
            },
            {
              "kind" : "text",
              "text" : ") -> "
            },
            {
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "s:s13OpaquePointerV",
              "text" : "OpaquePointer"
            }
          ]
        }
      ],
      "kind" : "declarations"
    },
    {
      "content" : [
        {
          "anchor" : "discussion",
          "level" : 2,
          "text" : "Discussion",
          "type" : "heading"
        },
        {
          "inlineContent" : [
            {
              "text" : "\\param hrp HRP of the utxo coin targeted",
              "type" : "text"
            },
            {
              "text" : " ",
              "type" : "text"
            },
            {
              "text" : "\\param publicKey Non-null pointer to the public key of the targeted coin",
              "type" : "text"
            },
            {
              "text" : " ",
              "type" : "text"
            },
            {
              "text" : "\\note should be deleted with \\TWSegwitAddressDelete",
              "type" : "text"
            },
            {
              "text" : " ",
              "type" : "text"
            },
            {
              "text" : "\\return Non-null pointer to the corresponding Segwit address",
              "type" : "text"
            }
          ],
          "type" : "paragraph"
        }
      ],
      "kind" : "content"
    }
  ],
  "schemaVersion" : {
    "major" : 0,
    "minor" : 3,
    "patch" : 0
  },
  "sections" : [

  ],
  "variants" : [
    {
      "paths" : [
        "\/documentation\/walletcore\/twsegwitaddresscreatewithpublickey(_:_:)"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "swift"
        }
      ]
    },
    {
      "paths" : [
        "\/documentation\/walletcore\/twsegwitaddresscreatewithpublickey(_:_:)"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "occ"
        }
      ]
    }
  ]
, 
"references": {
"doc://com.trustwallet.WalletCore/documentation/WalletCore": {
  "abstract" : [

  ],
  "identifier" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "WalletCore",
  "type" : "topic",
  "url" : "\/documentation\/walletcore"
},
"doc://com.trustwallet.WalletCore/documentation/WalletCore/TWHRP": {
  "abstract" : [
    {
      "text" : "Registered human-readable parts for BIP-0173",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "struct"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "TWHRP"
    }
  ],
  "identifier" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWHRP",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "TWHRP"
    }
  ],
  "role" : "symbol",
  "title" : "TWHRP",
  "type" : "topic",
  "url" : "\/documentation\/walletcore\/twhrp"
},
"doc://com.trustwallet.WalletCore/documentation/WalletCore/TWSegwitAddressCreateWithPublicKey(_:_:)": {
  "abstract" : [
    {
      "text" : "Creates a segwit-version-0 address from a public key and HRP prefix.",
      "type" : "text"
    },
    {
      "text" : " ",
      "type" : "text"
    },
    {
      "text" : "Taproot (v>=1) is not supported by this method.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "func"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "TWSegwitAddressCreateWithPublicKey"
    },
    {
      "kind" : "text",
      "text" : "("
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "c:@E@TWHRP",
      "text" : "TWHRP"
    },
    {
      "kind" : "text",
      "text" : ", "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:s13OpaquePointerV",
      "text" : "OpaquePointer"
    },
    {
      "kind" : "text",
      "text" : ") -> "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:s13OpaquePointerV",
      "text" : "OpaquePointer"
    }
  ],
  "identifier" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWSegwitAddressCreateWithPublicKey(_:_:)",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "TWSegwitAddressCreateWithPublicKey"
    }
  ],
  "role" : "symbol",
  "title" : "TWSegwitAddressCreateWithPublicKey(_:_:)",
  "type" : "topic",
  "url" : "\/documentation\/walletcore\/twsegwitaddresscreatewithpublickey(_:_:)"
}
}, 
"variantOverrides":[
  {
    "patch" : [
      {
        "op" : "replace",
        "path" : "\/identifier\/interfaceLanguage",
        "value" : "occ"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/roleHeading",
        "value" : "Function"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/title",
        "value" : "TWSegwitAddressCreateWithPublicKey"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/symbolKind",
        "value" : "func"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "TWSegwitAddressCreateWithPublicKey"
          }
        ]
      },
      {
        "op" : "add",
        "path" : "\/topicSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/relationshipsSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/seeAlsoSections",
        "value" : null
      },
      {
        "op" : "replace",
        "path" : "\/primaryContentSections\/0",
        "value" : {
          "declarations" : [
            {
              "languages" : [
                "occ"
              ],
              "platforms" : [
                "iOS"
              ],
              "tokens" : [
                {
                  "kind" : "keyword",
                  "text" : "extern"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "kind" : "keyword",
                  "text" : "struct"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:@S@TWSegwitAddress",
                  "text" : "TWSegwitAddress"
                },
                {
                  "kind" : "text",
                  "text" : " * "
                },
                {
                  "kind" : "identifier",
                  "text" : "TWSegwitAddressCreateWithPublicKey"
                },
                {
                  "kind" : "text",
                  "text" : "("
                },
                {
                  "kind" : "keyword",
                  "text" : "enum"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "identifier" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWHRP",
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:@E@TWHRP",
                  "text" : "TWHRP"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "kind" : "internalParam",
                  "text" : "hrp"
                },
                {
                  "kind" : "text",
                  "text" : ", "
                },
                {
                  "kind" : "keyword",
                  "text" : "struct"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:@S@TWPublicKey",
                  "text" : "TWPublicKey"
                },
                {
                  "kind" : "text",
                  "text" : " * "
                },
                {
                  "kind" : "internalParam",
                  "text" : "publicKey"
                },
                {
                  "kind" : "text",
                  "text" : ")"
                }
              ]
            }
          ],
          "kind" : "declarations"
        }
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.trustwallet.WalletCore~1documentation~1WalletCore~1TWHRP\/title",
        "value" : "TWHRP"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.trustwallet.WalletCore~1documentation~1WalletCore~1TWHRP\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "TWHRP"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.trustwallet.WalletCore~1documentation~1WalletCore~1TWSegwitAddressCreateWithPublicKey(_:_:)\/title",
        "value" : "TWSegwitAddressCreateWithPublicKey"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.trustwallet.WalletCore~1documentation~1WalletCore~1TWSegwitAddressCreateWithPublicKey(_:_:)\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "TWSegwitAddressCreateWithPublicKey"
          }
        ]
      }
    ],
    "traits" : [
      {
        "interfaceLanguage" : "occ"
      }
    ]
  }
]
}