{
  "abstract" : [
    {
      "text" : "Substrate based chains Address Type",
      "type" : "text"
    }
  ],
  "hierarchy" : {
    "paths" : [
      [
        "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore"
      ]
    ]
  },
  "identifier" : {
    "interfaceLanguage" : "swift",
    "url" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWSS58AddressType"
  },
  "kind" : "symbol",
  "metadata" : {
    "externalID" : "c:@E@TWSS58AddressType",
    "fragments" : [
      {
        "kind" : "keyword",
        "text" : "struct"
      },
      {
        "kind" : "text",
        "text" : " "
      },
      {
        "kind" : "identifier",
        "text" : "TWSS58AddressType"
      }
    ],
    "modules" : [
      {
        "name" : "WalletCore"
      }
    ],
    "navigatorTitle" : [
      {
        "kind" : "identifier",
        "text" : "TWSS58AddressType"
      }
    ],
    "role" : "symbol",
    "roleHeading" : "Structure",
    "symbolKind" : "struct",
    "title" : "TWSS58AddressType"
  },
  "primaryContentSections" : [
    {
      "declarations" : [
        {
          "languages" : [
            "swift"
          ],
          "platforms" : [
            "iOS"
          ],
          "tokens" : [
            {
              "kind" : "keyword",
              "text" : "struct"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "identifier",
              "text" : "TWSS58AddressType"
            }
          ]
        }
      ],
      "kind" : "declarations"
    },
    {
      "content" : [
        {
          "anchor" : "overview",
          "level" : 2,
          "text" : "Overview",
          "type" : "heading"
        },
        {
          "inlineContent" : [
            {
              "text" : "\\see https:\/\/github.com\/paritytech\/substrate\/wiki\/External-Address-Format-(SS58)#address-type",
              "type" : "text"
            }
          ],
          "type" : "paragraph"
        }
      ],
      "kind" : "content"
    }
  ],
  "relationshipsSections" : [
    {
      "identifiers" : [
        "doc:\/\/com.trustwallet.WalletCore\/SQ",
        "doc:\/\/com.trustwallet.WalletCore\/SY",
        "doc:\/\/com.trustwallet.WalletCore\/s8SendableP"
      ],
      "kind" : "relationships",
      "title" : "Conforms To",
      "type" : "conformsTo"
    }
  ],
  "schemaVersion" : {
    "major" : 0,
    "minor" : 3,
    "patch" : 0
  },
  "sections" : [

  ],
  "topicSections" : [
    {
      "identifiers" : [
        "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWSS58AddressType\/init(_:)",
        "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWSS58AddressType\/init(rawValue:)"
      ],
      "title" : "Initializers"
    },
    {
      "identifiers" : [
        "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWSS58AddressType\/rawValue"
      ],
      "title" : "Instance Properties"
    },
    {
      "generated" : true,
      "identifiers" : [
        "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWSS58AddressType\/Equatable-Implementations"
      ],
      "title" : "Default Implementations"
    }
  ],
  "variants" : [
    {
      "paths" : [
        "\/documentation\/walletcore\/twss58addresstype"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "swift"
        }
      ]
    },
    {
      "paths" : [
        "\/documentation\/walletcore\/twss58addresstype"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "occ"
        }
      ]
    }
  ]
, 
"references": {
"doc://com.trustwallet.WalletCore/SQ": {
  "identifier" : "doc:\/\/com.trustwallet.WalletCore\/SQ",
  "title" : "Swift.Equatable",
  "type" : "unresolvable"
},
"doc://com.trustwallet.WalletCore/SY": {
  "identifier" : "doc:\/\/com.trustwallet.WalletCore\/SY",
  "title" : "Swift.RawRepresentable",
  "type" : "unresolvable"
},
"doc://com.trustwallet.WalletCore/documentation/WalletCore": {
  "abstract" : [

  ],
  "identifier" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "WalletCore",
  "type" : "topic",
  "url" : "\/documentation\/walletcore"
},
"doc://com.trustwallet.WalletCore/documentation/WalletCore/TWSS58AddressType": {
  "abstract" : [
    {
      "text" : "Substrate based chains Address Type",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "struct"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "TWSS58AddressType"
    }
  ],
  "identifier" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWSS58AddressType",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "TWSS58AddressType"
    }
  ],
  "role" : "symbol",
  "title" : "TWSS58AddressType",
  "type" : "topic",
  "url" : "\/documentation\/walletcore\/twss58addresstype"
},
"doc://com.trustwallet.WalletCore/documentation/WalletCore/TWSS58AddressType/Equatable-Implementations": {
  "abstract" : [

  ],
  "identifier" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWSS58AddressType\/Equatable-Implementations",
  "kind" : "article",
  "role" : "collectionGroup",
  "title" : "Equatable Implementations",
  "type" : "topic",
  "url" : "\/documentation\/walletcore\/twss58addresstype\/equatable-implementations"
},
"doc://com.trustwallet.WalletCore/documentation/WalletCore/TWSS58AddressType/init(_:)": {
  "abstract" : [

  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "init"
    },
    {
      "kind" : "text",
      "text" : "("
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:s6UInt32V",
      "text" : "UInt32"
    },
    {
      "kind" : "text",
      "text" : ")"
    }
  ],
  "identifier" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWSS58AddressType\/init(_:)",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "init(_:)",
  "type" : "topic",
  "url" : "\/documentation\/walletcore\/twss58addresstype\/init(_:)"
},
"doc://com.trustwallet.WalletCore/documentation/WalletCore/TWSS58AddressType/init(rawValue:)": {
  "abstract" : [

  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "init"
    },
    {
      "kind" : "text",
      "text" : "("
    },
    {
      "kind" : "externalParam",
      "text" : "rawValue"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:s6UInt32V",
      "text" : "UInt32"
    },
    {
      "kind" : "text",
      "text" : ")"
    }
  ],
  "identifier" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWSS58AddressType\/init(rawValue:)",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "init(rawValue:)",
  "type" : "topic",
  "url" : "\/documentation\/walletcore\/twss58addresstype\/init(rawvalue:)"
},
"doc://com.trustwallet.WalletCore/documentation/WalletCore/TWSS58AddressType/rawValue": {
  "abstract" : [

  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "var"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "rawValue"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:s6UInt32V",
      "text" : "UInt32"
    }
  ],
  "identifier" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWSS58AddressType\/rawValue",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "rawValue",
  "type" : "topic",
  "url" : "\/documentation\/walletcore\/twss58addresstype\/rawvalue"
},
"doc://com.trustwallet.WalletCore/s8SendableP": {
  "identifier" : "doc:\/\/com.trustwallet.WalletCore\/s8SendableP",
  "title" : "Swift.Sendable",
  "type" : "unresolvable"
}
}, 
"variantOverrides":[
  {
    "patch" : [
      {
        "op" : "replace",
        "path" : "\/identifier\/interfaceLanguage",
        "value" : "occ"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/roleHeading",
        "value" : "Enumeration"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/title",
        "value" : "TWSS58AddressType"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/symbolKind",
        "value" : "enum"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "TWSS58AddressType"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/navigatorTitle",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "TWSS58AddressType"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/topicSections",
        "value" : null
      },
      {
        "op" : "replace",
        "path" : "\/relationshipsSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/seeAlsoSections",
        "value" : null
      },
      {
        "op" : "replace",
        "path" : "\/primaryContentSections\/0",
        "value" : {
          "declarations" : [
            {
              "languages" : [
                "occ"
              ],
              "platforms" : [
                "iOS"
              ],
              "tokens" : [
                {
                  "kind" : "keyword",
                  "text" : "enum"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "kind" : "identifier",
                  "text" : "TWSS58AddressType"
                },
                {
                  "kind" : "text",
                  "text" : ": "
                },
                {
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:i",
                  "text" : "unsigned int"
                }
              ]
            }
          ],
          "kind" : "declarations"
        }
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.trustwallet.WalletCore~1documentation~1WalletCore~1TWSS58AddressType\/title",
        "value" : "TWSS58AddressType"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.trustwallet.WalletCore~1documentation~1WalletCore~1TWSS58AddressType\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "TWSS58AddressType"
          }
        ]
      }
    ],
    "traits" : [
      {
        "interfaceLanguage" : "occ"
      }
    ]
  }
]
}