{
  "hierarchy" : {
    "paths" : [
      [
        "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore"
      ]
    ]
  },
  "identifier" : {
    "interfaceLanguage" : "swift",
    "url" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWSS58AddressTypePolkadot"
  },
  "kind" : "symbol",
  "metadata" : {
    "externalID" : "c:@E@TWSS58AddressType@TWSS58AddressTypePolkadot",
    "fragments" : [
      {
        "kind" : "keyword",
        "text" : "var"
      },
      {
        "kind" : "text",
        "text" : " "
      },
      {
        "kind" : "identifier",
        "text" : "TWSS58AddressTypePolkadot"
      },
      {
        "kind" : "text",
        "text" : ": "
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "c:@E@TWSS58AddressType",
        "text" : "TWSS58AddressType"
      }
    ],
    "modules" : [
      {
        "name" : "WalletCore"
      }
    ],
    "navigatorTitle" : [
      {
        "kind" : "identifier",
        "text" : "TWSS58AddressTypePolkadot"
      }
    ],
    "role" : "symbol",
    "roleHeading" : "Global Variable",
    "symbolKind" : "var",
    "title" : "TWSS58AddressTypePolkadot"
  },
  "primaryContentSections" : [
    {
      "declarations" : [
        {
          "languages" : [
            "swift"
          ],
          "platforms" : [
            "iOS"
          ],
          "tokens" : [
            {
              "kind" : "keyword",
              "text" : "var"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "identifier",
              "text" : "TWSS58AddressTypePolkadot"
            },
            {
              "kind" : "text",
              "text" : ": "
            },
            {
              "identifier" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWSS58AddressType",
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "c:@E@TWSS58AddressType",
              "text" : "TWSS58AddressType"
            },
            {
              "kind" : "text",
              "text" : " { "
            },
            {
              "kind" : "keyword",
              "text" : "get"
            },
            {
              "kind" : "text",
              "text" : " }"
            }
          ]
        }
      ],
      "kind" : "declarations"
    }
  ],
  "schemaVersion" : {
    "major" : 0,
    "minor" : 3,
    "patch" : 0
  },
  "sections" : [

  ],
  "variants" : [
    {
      "paths" : [
        "\/documentation\/walletcore\/twss58addresstypepolkadot"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "swift"
        }
      ]
    },
    {
      "paths" : [
        "\/documentation\/walletcore\/twss58addresstypepolkadot"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "occ"
        }
      ]
    }
  ]
, 
"references": {
"doc://com.trustwallet.WalletCore/documentation/WalletCore": {
  "abstract" : [

  ],
  "identifier" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "WalletCore",
  "type" : "topic",
  "url" : "\/documentation\/walletcore"
},
"doc://com.trustwallet.WalletCore/documentation/WalletCore/TWSS58AddressType": {
  "abstract" : [
    {
      "text" : "Substrate based chains Address Type",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "struct"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "TWSS58AddressType"
    }
  ],
  "identifier" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWSS58AddressType",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "TWSS58AddressType"
    }
  ],
  "role" : "symbol",
  "title" : "TWSS58AddressType",
  "type" : "topic",
  "url" : "\/documentation\/walletcore\/twss58addresstype"
},
"doc://com.trustwallet.WalletCore/documentation/WalletCore/TWSS58AddressTypePolkadot": {
  "abstract" : [

  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "var"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "TWSS58AddressTypePolkadot"
    },
    {
      "kind" : "text",
      "text" : ": "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "c:@E@TWSS58AddressType",
      "text" : "TWSS58AddressType"
    }
  ],
  "identifier" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWSS58AddressTypePolkadot",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "TWSS58AddressTypePolkadot"
    }
  ],
  "role" : "symbol",
  "title" : "TWSS58AddressTypePolkadot",
  "type" : "topic",
  "url" : "\/documentation\/walletcore\/twss58addresstypepolkadot"
}
}, 
"variantOverrides":[
  {
    "patch" : [
      {
        "op" : "replace",
        "path" : "\/identifier\/interfaceLanguage",
        "value" : "occ"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/roleHeading",
        "value" : "Enumeration Case"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/title",
        "value" : "TWSS58AddressTypePolkadot"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/symbolKind",
        "value" : "case"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "TWSS58AddressTypePolkadot"
          }
        ]
      },
      {
        "op" : "add",
        "path" : "\/topicSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/relationshipsSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/seeAlsoSections",
        "value" : null
      },
      {
        "op" : "replace",
        "path" : "\/primaryContentSections\/0",
        "value" : {
          "declarations" : [
            {
              "languages" : [
                "occ"
              ],
              "platforms" : [
                "iOS"
              ],
              "tokens" : [
                {
                  "kind" : "identifier",
                  "text" : "TWSS58AddressTypePolkadot"
                }
              ]
            }
          ],
          "kind" : "declarations"
        }
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.trustwallet.WalletCore~1documentation~1WalletCore~1TWSS58AddressType\/title",
        "value" : "TWSS58AddressType"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.trustwallet.WalletCore~1documentation~1WalletCore~1TWSS58AddressType\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "TWSS58AddressType"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.trustwallet.WalletCore~1documentation~1WalletCore~1TWSS58AddressTypePolkadot\/title",
        "value" : "TWSS58AddressTypePolkadot"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.trustwallet.WalletCore~1documentation~1WalletCore~1TWSS58AddressTypePolkadot\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "TWSS58AddressTypePolkadot"
          }
        ]
      }
    ],
    "traits" : [
      {
        "interfaceLanguage" : "occ"
      }
    ]
  }
]
}