{
  "abstract" : [
    {
      "text" : "Compiles a complete transation with one or more external signatures.",
      "type" : "text"
    }
  ],
  "hierarchy" : {
    "paths" : [
      [
        "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore"
      ]
    ]
  },
  "identifier" : {
    "interfaceLanguage" : "swift",
    "url" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWTransactionCompilerCompileWithSignatures(_:_:_:_:)"
  },
  "kind" : "symbol",
  "metadata" : {
    "externalID" : "c:@F@TWTransactionCompilerCompileWithSignatures",
    "fragments" : [
      {
        "kind" : "keyword",
        "text" : "func"
      },
      {
        "kind" : "text",
        "text" : " "
      },
      {
        "kind" : "identifier",
        "text" : "TWTransactionCompilerCompileWithSignatures"
      },
      {
        "kind" : "text",
        "text" : "("
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "c:@E@TWCoinType",
        "text" : "TWCoinType"
      },
      {
        "kind" : "text",
        "text" : ", "
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "s:SV",
        "text" : "UnsafeRawPointer"
      },
      {
        "kind" : "text",
        "text" : ", "
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "s:s13OpaquePointerV",
        "text" : "OpaquePointer"
      },
      {
        "kind" : "text",
        "text" : ", "
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "s:s13OpaquePointerV",
        "text" : "OpaquePointer"
      },
      {
        "kind" : "text",
        "text" : ") -> "
      },
      {
        "kind" : "typeIdentifier",
        "preciseIdentifier" : "s:SV",
        "text" : "UnsafeRawPointer"
      }
    ],
    "modules" : [
      {
        "name" : "WalletCore"
      }
    ],
    "navigatorTitle" : [
      {
        "kind" : "identifier",
        "text" : "TWTransactionCompilerCompileWithSignatures"
      }
    ],
    "role" : "symbol",
    "roleHeading" : "Function",
    "symbolKind" : "func",
    "title" : "TWTransactionCompilerCompileWithSignatures(_:_:_:_:)"
  },
  "primaryContentSections" : [
    {
      "declarations" : [
        {
          "languages" : [
            "swift"
          ],
          "platforms" : [
            "iOS"
          ],
          "tokens" : [
            {
              "kind" : "keyword",
              "text" : "func"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "identifier",
              "text" : "TWTransactionCompilerCompileWithSignatures"
            },
            {
              "kind" : "text",
              "text" : "("
            },
            {
              "kind" : "externalParam",
              "text" : "_"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "internalParam",
              "text" : "coinType"
            },
            {
              "kind" : "text",
              "text" : ": "
            },
            {
              "identifier" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWCoinType",
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "c:@E@TWCoinType",
              "text" : "TWCoinType"
            },
            {
              "kind" : "text",
              "text" : ", "
            },
            {
              "kind" : "externalParam",
              "text" : "_"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "internalParam",
              "text" : "txInputData"
            },
            {
              "kind" : "text",
              "text" : ": "
            },
            {
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "s:SV",
              "text" : "UnsafeRawPointer"
            },
            {
              "kind" : "text",
              "text" : ", "
            },
            {
              "kind" : "externalParam",
              "text" : "_"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "internalParam",
              "text" : "signatures"
            },
            {
              "kind" : "text",
              "text" : ": "
            },
            {
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "s:s13OpaquePointerV",
              "text" : "OpaquePointer"
            },
            {
              "kind" : "text",
              "text" : ", "
            },
            {
              "kind" : "externalParam",
              "text" : "_"
            },
            {
              "kind" : "text",
              "text" : " "
            },
            {
              "kind" : "internalParam",
              "text" : "publicKeys"
            },
            {
              "kind" : "text",
              "text" : ": "
            },
            {
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "s:s13OpaquePointerV",
              "text" : "OpaquePointer"
            },
            {
              "kind" : "text",
              "text" : ") -> "
            },
            {
              "kind" : "typeIdentifier",
              "preciseIdentifier" : "s:SV",
              "text" : "UnsafeRawPointer"
            }
          ]
        }
      ],
      "kind" : "declarations"
    },
    {
      "content" : [
        {
          "anchor" : "discussion",
          "level" : 2,
          "text" : "Discussion",
          "type" : "heading"
        },
        {
          "inlineContent" : [
            {
              "text" : "Puts together from transaction input and provided public keys and signatures. The signatures must match the hashes",
              "type" : "text"
            },
            {
              "text" : " ",
              "type" : "text"
            },
            {
              "text" : "returned by TWTransactionCompilerPreImageHashes, in the same order. The publicKeyHash attached",
              "type" : "text"
            },
            {
              "text" : " ",
              "type" : "text"
            },
            {
              "text" : "to the hashes enable identifying the private key needed for signing the hash.",
              "type" : "text"
            },
            {
              "text" : " ",
              "type" : "text"
            },
            {
              "text" : "\\param coin coin type.",
              "type" : "text"
            },
            {
              "text" : " ",
              "type" : "text"
            },
            {
              "text" : "\\param txInputData The serialized data of a signing input.",
              "type" : "text"
            },
            {
              "text" : " ",
              "type" : "text"
            },
            {
              "text" : "\\param signatures signatures to compile, using TWDataVector.",
              "type" : "text"
            },
            {
              "text" : " ",
              "type" : "text"
            },
            {
              "text" : "\\param publicKeys public keys for signers to match private keys, using TWDataVector.",
              "type" : "text"
            },
            {
              "text" : " ",
              "type" : "text"
            },
            {
              "text" : "\\return serialized data of a proto object ",
              "type" : "text"
            },
            {
              "code" : "SigningOutput",
              "type" : "codeVoice"
            },
            {
              "text" : ".",
              "type" : "text"
            }
          ],
          "type" : "paragraph"
        }
      ],
      "kind" : "content"
    }
  ],
  "schemaVersion" : {
    "major" : 0,
    "minor" : 3,
    "patch" : 0
  },
  "sections" : [

  ],
  "variants" : [
    {
      "paths" : [
        "\/documentation\/walletcore\/twtransactioncompilercompilewithsignatures(_:_:_:_:)"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "swift"
        }
      ]
    },
    {
      "paths" : [
        "\/documentation\/walletcore\/twtransactioncompilercompilewithsignatures(_:_:_:_:)"
      ],
      "traits" : [
        {
          "interfaceLanguage" : "occ"
        }
      ]
    }
  ]
, 
"references": {
"doc://com.trustwallet.WalletCore/documentation/WalletCore": {
  "abstract" : [

  ],
  "identifier" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore",
  "kind" : "symbol",
  "role" : "collection",
  "title" : "WalletCore",
  "type" : "topic",
  "url" : "\/documentation\/walletcore"
},
"doc://com.trustwallet.WalletCore/documentation/WalletCore/TWCoinType": {
  "abstract" : [
    {
      "text" : "Coin type for Level 2 of BIP44.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "struct"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "TWCoinType"
    }
  ],
  "identifier" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWCoinType",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "TWCoinType"
    }
  ],
  "role" : "symbol",
  "title" : "TWCoinType",
  "type" : "topic",
  "url" : "\/documentation\/walletcore\/twcointype"
},
"doc://com.trustwallet.WalletCore/documentation/WalletCore/TWData": {
  "abstract" : [
    {
      "text" : "Defines a resizable block of data.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "identifier",
      "text" : "TWData"
    }
  ],
  "identifier" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWData",
  "kind" : "symbol",
  "role" : "symbol",
  "title" : "TWData",
  "type" : "topic",
  "url" : "\/documentation\/walletcore\/twdata"
},
"doc://com.trustwallet.WalletCore/documentation/WalletCore/TWTransactionCompilerCompileWithSignatures(_:_:_:_:)": {
  "abstract" : [
    {
      "text" : "Compiles a complete transation with one or more external signatures.",
      "type" : "text"
    }
  ],
  "fragments" : [
    {
      "kind" : "keyword",
      "text" : "func"
    },
    {
      "kind" : "text",
      "text" : " "
    },
    {
      "kind" : "identifier",
      "text" : "TWTransactionCompilerCompileWithSignatures"
    },
    {
      "kind" : "text",
      "text" : "("
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "c:@E@TWCoinType",
      "text" : "TWCoinType"
    },
    {
      "kind" : "text",
      "text" : ", "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:SV",
      "text" : "UnsafeRawPointer"
    },
    {
      "kind" : "text",
      "text" : ", "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:s13OpaquePointerV",
      "text" : "OpaquePointer"
    },
    {
      "kind" : "text",
      "text" : ", "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:s13OpaquePointerV",
      "text" : "OpaquePointer"
    },
    {
      "kind" : "text",
      "text" : ") -> "
    },
    {
      "kind" : "typeIdentifier",
      "preciseIdentifier" : "s:SV",
      "text" : "UnsafeRawPointer"
    }
  ],
  "identifier" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWTransactionCompilerCompileWithSignatures(_:_:_:_:)",
  "kind" : "symbol",
  "navigatorTitle" : [
    {
      "kind" : "identifier",
      "text" : "TWTransactionCompilerCompileWithSignatures"
    }
  ],
  "role" : "symbol",
  "title" : "TWTransactionCompilerCompileWithSignatures(_:_:_:_:)",
  "type" : "topic",
  "url" : "\/documentation\/walletcore\/twtransactioncompilercompilewithsignatures(_:_:_:_:)"
}
}, 
"variantOverrides":[
  {
    "patch" : [
      {
        "op" : "replace",
        "path" : "\/identifier\/interfaceLanguage",
        "value" : "occ"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/roleHeading",
        "value" : "Function"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/title",
        "value" : "TWTransactionCompilerCompileWithSignatures"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/symbolKind",
        "value" : "func"
      },
      {
        "op" : "replace",
        "path" : "\/metadata\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "TWTransactionCompilerCompileWithSignatures"
          }
        ]
      },
      {
        "op" : "add",
        "path" : "\/topicSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/relationshipsSections",
        "value" : null
      },
      {
        "op" : "add",
        "path" : "\/seeAlsoSections",
        "value" : null
      },
      {
        "op" : "replace",
        "path" : "\/primaryContentSections\/0",
        "value" : {
          "declarations" : [
            {
              "languages" : [
                "occ"
              ],
              "platforms" : [
                "iOS"
              ],
              "tokens" : [
                {
                  "kind" : "keyword",
                  "text" : "extern"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "identifier" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWData",
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:TWData.h@T@TWData",
                  "text" : "TWData"
                },
                {
                  "kind" : "text",
                  "text" : " * "
                },
                {
                  "kind" : "identifier",
                  "text" : "TWTransactionCompilerCompileWithSignatures"
                },
                {
                  "kind" : "text",
                  "text" : "("
                },
                {
                  "kind" : "keyword",
                  "text" : "enum"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "identifier" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWCoinType",
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:@E@TWCoinType",
                  "text" : "TWCoinType"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "kind" : "internalParam",
                  "text" : "coinType"
                },
                {
                  "kind" : "text",
                  "text" : ", "
                },
                {
                  "identifier" : "doc:\/\/com.trustwallet.WalletCore\/documentation\/WalletCore\/TWData",
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:TWData.h@T@TWData",
                  "text" : "TWData"
                },
                {
                  "kind" : "text",
                  "text" : " * "
                },
                {
                  "kind" : "internalParam",
                  "text" : "txInputData"
                },
                {
                  "kind" : "text",
                  "text" : ", "
                },
                {
                  "kind" : "keyword",
                  "text" : "const"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "kind" : "keyword",
                  "text" : "struct"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:@S@TWDataVector",
                  "text" : "TWDataVector"
                },
                {
                  "kind" : "text",
                  "text" : " * "
                },
                {
                  "kind" : "internalParam",
                  "text" : "signatures"
                },
                {
                  "kind" : "text",
                  "text" : ", "
                },
                {
                  "kind" : "keyword",
                  "text" : "const"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "kind" : "keyword",
                  "text" : "struct"
                },
                {
                  "kind" : "text",
                  "text" : " "
                },
                {
                  "kind" : "typeIdentifier",
                  "preciseIdentifier" : "c:@S@TWDataVector",
                  "text" : "TWDataVector"
                },
                {
                  "kind" : "text",
                  "text" : " * "
                },
                {
                  "kind" : "internalParam",
                  "text" : "publicKeys"
                },
                {
                  "kind" : "text",
                  "text" : ")"
                }
              ]
            }
          ],
          "kind" : "declarations"
        }
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.trustwallet.WalletCore~1documentation~1WalletCore~1TWCoinType\/title",
        "value" : "TWCoinType"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.trustwallet.WalletCore~1documentation~1WalletCore~1TWCoinType\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "TWCoinType"
          }
        ]
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.trustwallet.WalletCore~1documentation~1WalletCore~1TWTransactionCompilerCompileWithSignatures(_:_:_:_:)\/title",
        "value" : "TWTransactionCompilerCompileWithSignatures"
      },
      {
        "op" : "replace",
        "path" : "\/references\/doc:~1~1com.trustwallet.WalletCore~1documentation~1WalletCore~1TWTransactionCompilerCompileWithSignatures(_:_:_:_:)\/fragments",
        "value" : [
          {
            "kind" : "identifier",
            "text" : "TWTransactionCompilerCompileWithSignatures"
          }
        ]
      }
    ],
    "traits" : [
      {
        "interfaceLanguage" : "occ"
      }
    ]
  }
]
}